---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-14 18:13
---
local typedefs = require "kong.db.schema.typedefs"

return {
    name = "ejuoauthclient",
    fields = {

                { run_on = typedefs.run_on },
                { protocols = typedefs.protocols_http },

                { config = {
                            type = "record",

                            fields = {

                                        { tokenURL = { type = "string", required = true, default = "/token" } },
                                        { clientId = { type = "string", required = true, default = "clientId" } },
                                        { clientSecret = { type = "string", required = true, default = "clientSecret123" } },

                                        { redisHost = { type = "string", required = true, } },
                                        { redisPort = { type = "number", required = true, default = 6379, } },
                                        { redisTimeout = { type = "number", required = true, default = 2000, } },

                                        { cookiesName = { type = "string", required = true, } },
                                        { tokenPrefix = { type = "string", required = true, } },


                            },

                            },

                },

               },

}